### ISSUE TITLE
Cannot use extensions because they try to access UI thread from bundle start method

### ISSUE THREAD

**Issue by davidburkhart** [eclipse/swtchart#452]
When I update my application to 1.0.0 I cannot start the extensions bundle. The chart bundle itself works fine.

When the extension bundle is used, I get this stacktrace:

```
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.swtchart.extensions.core.ResourceSupport
	at org.eclipse.swtchart.extensions.internal.mappings.MappingsIO.restoreSettings(MappingsIO.java:101)
	at org.eclipse.swtchart.extensions.Activator.start(Activator.java:42)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:826)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:768)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1066)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:394)
	at org.eclipse.osgi.container.Module.doStart(Module.java:643)
	at org.eclipse.osgi.container.Module.start(Module.java:500)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:528)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:122)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:622)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:353)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:417)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:525)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:438)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:195)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at my.own.NicePerspective.createInitialLayout(NicePerspective.java:29)
	at org.eclipse.ui.internal.WorkbenchPage.createPerspective(WorkbenchPage.java:4104)
	at org.eclipse.ui.internal.WorkbenchPage.busySetPerspective(WorkbenchPage.java:4009)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$12(WorkbenchPage.java:3969)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:3969)
	at org.eclipse.ui.handlers.ShowPerspectiveHandler.openPerspective(ShowPerspectiveHandler.java:156)
	at org.eclipse.ui.handlers.ShowPerspectiveHandler.lambda$1(ShowPerspectiveHandler.java:124)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.handlers.ShowPerspectiveHandler.openOther(ShowPerspectiveHandler.java:119)
	at org.eclipse.ui.handlers.ShowPerspectiveHandler.execute(ShowPerspectiveHandler.java:57)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:277)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:186)
	at org.eclipse.e4.ui.workbench.addons.perspectiveswitcher.PerspectiveSwitcher.selectPerspective(PerspectiveSwitcher.java:554)
	at org.eclipse.e4.ui.workbench.addons.perspectiveswitcher.PerspectiveSwitcher.lambda$3(PerspectiveSwitcher.java:312)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:83)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:286)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5862)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1652)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4524)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:668)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:576)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:178)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:149)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:467)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:670)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:607)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1492)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1465)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException: This is not an UI thread (or Device already disposed) [in thread "Start Level: Equinox Container: a17b4077-0673-46b1-91a9-33702010b55f"]
	at java.base/java.util.Objects.requireNonNull(Objects.java:259)
	at org.eclipse.jface.resource.JFaceResources.getResources(JFaceResources.java:243)
	at org.eclipse.swtchart.extensions.core.ResourceSupport.<clinit>(ResourceSupport.java:75)
	at org.eclipse.swtchart.extensions.internal.mappings.MappingsIO.restoreSettings(MappingsIO.java:101)
	at org.eclipse.swtchart.extensions.Activator.start(Activator.java:42)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:826)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:768)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1066)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:394)
	at org.eclipse.osgi.container.Module.doStart(Module.java:643)
	at org.eclipse.osgi.container.Module.start(Module.java:500)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2111)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:146)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2102)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2044)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:2004)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1916)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```

I use those bundles:
* `org.eclipse.swtchart`
* `org.eclipse.swtchart.extensions`

I use this p2 repo: https://download.eclipse.org/releases/2025-03

My perspective has a Chart-View that extends Either Chart (without extensions, working) or InteractiveChart (with extensions producing the error above).

Am I using the extensions wrong? Or is that a general bug where the start method should use `Display.asyncExec` to do `MappingsIO.restoreSettings` in UI thread?

**Comment by eselmeister** [comment]
@davidburkhart Do you get the same error when you run the demo chart?
`org.eclipse.swtchart.extensions.examples.charts.DemoChart.java`

**Comment by davidburkhart** [comment]
@eselmeister that works, but that is also not starting swtchart as osgi bundles. I am using swtchart in an eclipse rcp application as regular osgi bundles. I was updating from `0.9.0` which was working still. 

As I read my stacktrace, when the view using extension is being built, classes from extensions have to be loaded. Therefor osgi tries to start the bundle to load the classes. The start method of an osgi bundle is not being called in the ui thread and therefore extensions should run any code requiring a `Display`, or if should use `Display.asyncExec`.

In the specific case here it would not be even needed, because the `org.eclipse.swtchart.extensions.core.ResourceSupport` is being accessed to get a `PreferenceStore`. That method would not need any Display, but `ResourceSupport` has this field which accesses code that needs a `Display` via `JFaceResources`. That is only needed to load images, but not necessary for the access to the `PreferenceStore`:

```
private static ResourceManager resourceManager = new LocalResourceManager(JFaceResources.getResources());
```

**Comment by eselmeister** [comment]
We are using it also in a RCP environment. I have created a demo RCP using SWTChart and extension. Could you try to execute it in your side? My environment doesn't show error messages.

[org.eclipse.swtchart.extensions.rcpdemo.zip](https://github.com/user-attachments/files/19724086/org.eclipse.swtchart.extensions.rcpdemo.zip)

![Image](https://github.com/user-attachments/assets/367f5f9f-89bf-4bf8-8c78-bfdf3072d871)

**Comment by davidburkhart** [comment]
Yes that works. The stacktrace looks different, theres a `Display.syncExec` in the stacktrace.

Somehow for me the extensions bundle gets activated differently. Is that maybe connected to my "classic application" vs an e4 application in your demo? Or are there other factors influencing the activation of bundles? I am not an expert in osgi and also recent rcp development...

```
Thread [main] (Suspended (breakpoint at line 242 in JFaceResources))	
	JFaceResources.getResources() line: 242	
	ResourceSupport.<clinit>() line: 76	
	MappingsIO.restoreSettings() line: 101	
	Activator.start(BundleContext) line: 42	
	BundleContextImpl$2.run() line: 826	
	BundleContextImpl$2.run() line: 1	
	AccessController.executePrivileged(PrivilegedExceptionAction<T>, AccessControlContext, Class<?>) line: 809	
	AccessController.doPrivileged(PrivilegedExceptionAction<T>) line: 571	
	BundleContextImpl.startActivator(BundleActivator) line: 818	
	BundleContextImpl.start() line: 768	
	EquinoxBundle.startWorker0() line: 1066	
	EquinoxBundle$EquinoxModule.startWorker() line: 394	
	EquinoxBundle$EquinoxModule(Module).doStart(Module$StartOptions...) line: 643	
	EquinoxBundle$EquinoxModule(Module).start(Module$StartOptions...) line: 500	
	SecureAction.start(Module, Module$StartOptions...) line: 528	
	EclipseLazyStarter.postFindLocalClass(String, Class<?>, ClasspathManager) line: 122	
	ClasspathManager.findLocalClass(String) line: 622	
	EquinoxClassLoader(ModuleClassLoader).findLocalClass(String) line: 353	
	BundleLoader.findLocalClass(String) line: 417	
	BundleLoader.findClass0(String, boolean, boolean) line: 525	
	BundleLoader.findClass(String) line: 438	
	EquinoxClassLoader(ModuleClassLoader).loadClass(String, boolean) line: 195	
	EquinoxClassLoader(ClassLoader).loadClass(String) line: 526	
	Class<T>.getDeclaredFields0(boolean) line: not available [native method]	
	Class<T>.privateGetDeclaredFields(boolean) line: 3473	
	Class<T>.getDeclaredFields() line: 2542	
	InjectorImpl.getDeclaredFields(Class<?>) line: 820	
	InjectorImpl.processFields(Object, PrimaryObjectSupplier, PrimaryObjectSupplier, Class<?>, boolean, List<Requestor<?>>) line: 679	
	InjectorImpl.processClass(Object, PrimaryObjectSupplier, PrimaryObjectSupplier, Class<?>, ArrayList<Class<?>>, boolean, boolean, List<Requestor<?>>) line: 652	
	InjectorImpl.processClassHierarchy(Object, PrimaryObjectSupplier, PrimaryObjectSupplier, boolean, boolean, List<Requestor<?>>) line: 633	
	InjectorImpl.internalInject(Object, PrimaryObjectSupplier, PrimaryObjectSupplier) line: 115	
	InjectorImpl.internalMake(Class<?>, PrimaryObjectSupplier, PrimaryObjectSupplier) line: 386	
	InjectorImpl.make(Class<T>, PrimaryObjectSupplier) line: 312	
	ContextInjectionFactory.make(Class<T>, IEclipseContext) line: 203	
	ReflectionContributionFactory.createFromBundle(Bundle, IEclipseContext, IEclipseContext, URI) line: 90	
	ReflectionContributionFactory.doCreate(String, IEclipseContext, IEclipseContext) line: 59	
	ReflectionContributionFactory.create(String, IEclipseContext) line: 42	
	ContributedPartRenderer.createWidget(MUIElement, Object) line: 134	
	PartRenderingEngine.createWidget(MUIElement, Object) line: 991	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 658	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 762	
	PartRenderingEngine$2.run() line: 727	
	SafeRunner.run(ISafeRunnable) line: 47	
	PartRenderingEngine.createGui(MUIElement) line: 711	
	StackRenderer.showTab(MUIElement) line: 1389	
	StackRenderer(LazyStackRenderer).lambda$0(Event) line: 84	
	Lambda.handleEvent(Event) line: not available	
	UIEventHandler.lambda$0(Event) line: 38	
	Lambda.run() line: not available	
	Synchronizer.syncExec(Runnable) line: 183	
	Display.syncExec(Runnable) line: 5967	
	DisplayUISynchronize.syncExec(Runnable) line: 34	
	UIEventHandler.handleEvent(Event) line: 38	
	EventHandlerWrapper.handleEvent(Event, Permission) line: 206	
	EventHandlerTracker.dispatchEvent(EventHandlerWrapper, Permission, int, Event) line: 201	
	EventHandlerTracker.dispatchEvent(Object, Object, int, Object) line: 1	
	EventManager.dispatchEvent(Set<Entry<K,V>>, EventDispatcher<K,V,E>, int, E) line: 230	
	ListenerQueue<K,V,E>.dispatchEventSynchronous(int, E) line: 151	
	EventAdminImpl.dispatchEvent(Event, boolean) line: 131	
	EventAdminImpl.sendEvent(Event) line: 73	
	EventComponent.sendEvent(Event) line: 44	
	EventBroker.send(String, Object) line: 55	
	UIEventPublisher.notifyChanged(Notification) line: 60	
	PartStackImpl(BasicNotifierImpl).eNotify(Notification) line: 424	
	PartStackImpl(ElementContainerImpl<T>).setSelectedElementGen(T) line: 168	
	PartStackImpl(ElementContainerImpl<T>).setSelectedElement(T) line: 187	
	StackRenderer(LazyStackRenderer).postProcess(MUIElement) line: 119	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 676	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 762	
	PartRenderingEngine$2.run() line: 727	
	SafeRunner.run(ISafeRunnable) line: 47	
	PartRenderingEngine.createGui(MUIElement) line: 711	
	SashRenderer(SWTPartRenderer).processContents(MElementContainer<MUIElement>) line: 72	
	SashRenderer.processContents(MElementContainer<MUIElement>) line: 147	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 672	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 762	
	PartRenderingEngine$2.run() line: 727	
	SafeRunner.run(ISafeRunnable) line: 47	
	PartRenderingEngine.createGui(MUIElement) line: 711	
	WBWRenderer(SWTPartRenderer).processContents(MElementContainer<MUIElement>) line: 72	
	WBWRenderer.processContents(MElementContainer<MUIElement>) line: 662	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 672	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 762	
	PartRenderingEngine$2.run() line: 727	
	SafeRunner.run(ISafeRunnable) line: 47	
	PartRenderingEngine.createGui(MUIElement) line: 711	
	PartRenderingEngine$5.run() line: 1079	
	Realm.runWithDefault(Realm, Runnable) line: 339	
	PartRenderingEngine.run(MApplicationElement, IEclipseContext) line: 1042	
	E4Workbench.createAndRunUI(MApplicationElement) line: 153	
	E4Application.start(IApplicationContext) line: 165	
	EclipseAppHandle.run(Object) line: 208	
	EclipseAppLauncher.runApplication(Object) line: 149	
	EclipseAppLauncher.start(Object) line: 115	
	EclipseStarter.run(Object) line: 467	
	EclipseStarter.run(String[], Runnable) line: 298	
	DirectMethodHandle$Holder.invokeStatic(Object, Object, Object) line: not available	
	0x00007941e8007800.invoke(Object, Object, Object, Object) line: not available	
	0x00007941e8007c00.invokeExact_MT(Object, Object, Object, Object, Object) line: not available	
	DirectMethodHandleAccessor.invokeImpl(Object, Object[]) line: 155	
	DirectMethodHandleAccessor.invoke(Object, Object[]) line: 103	
	Method.invoke(Object, Object...) line: 580	
	Main.invokeFramework(String[], URL[]) line: 670	
	Main.basicRun(String[]) line: 607	
	Main.run(String[]) line: 1492	
	Main.main(String[]) line: 1465	
```

**Comment by eselmeister** [comment]
OSGi allows to define start levels, but none is specified in the demo RCP.
![Image](https://github.com/user-attachments/assets/5521420f-b809-47ed-a01d-0098de6380d5)

Please try to create a small RCP application that crashes on your side. I will then inspect it.

**Comment by davidburkhart** [comment]
I got it to work by setting "Default Auto-Start" to `false`. Thanks for the hint with the start levels.

![Image](https://github.com/user-attachments/assets/f5a1d642-1ae9-4991-a4e5-0ad42e37a5ac)
